### GET

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5deaa54ff1ddb7012ebb3a34

###

GET http://localhost:3001/api/persons/wrongid

### unknown endpoint

GET http://localhost:3001/api/unknown

### POST

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "555-233-4567"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "555-233-4567"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mike Test"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mike Test",
  "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "1234-123-12345"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "1234-123-12345"
}

### DELETE

DELETE http://localhost:3001/api/persons/1