POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "555-233-4567"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "555-233-4567"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mike Test"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mike Test",
  "number": ""
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "1234-123-12345"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "1234-123-12345"
}